from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Stock(models.Model):
    date = models.DateField()
    symbol = models.TextField()
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    close = models.FloatField()
    volume = models.FloatField()
    dividends = models.FloatField()
    stocksplits = models.FloatField()


class Symbol(models.Model):
    id = models.UUIDField(primary_key=True)
    symbol_name = models.TextField(null=True)
    weekchange = models.TextField(null=True)
    sandp52weekchange = models.TextField(null=True)
    address1 = models.TextField(null=True)
    algorithm = models.TextField(null=True)
    annualholdingsturnover = models.TextField(null=True)
    annualreportexpenseratio = models.TextField(null=True)
    ask = models.TextField(null=True)
    asksize = models.TextField(null=True)
    averagedailyvolume10day = models.TextField(null=True)
    averagevolume = models.TextField(null=True)
    averagevolume10days = models.TextField(null=True)
    beta = models.TextField(null=True)
    beta3year = models.TextField(null=True)
    bid = models.TextField(null=True)
    bidsize = models.TextField(null=True)
    bookvalue = models.TextField(null=True)
    category = models.TextField(null=True)
    circulatingsupply = models.TextField(null=True)
    city = models.TextField(null=True)
    companyofficers = models.TextField(null=True)
    country = models.TextField(null=True)
    currency = models.TextField(null=True)
    dateshortinterest = models.TextField(null=True)
    dayhigh = models.TextField(null=True)
    daylow = models.TextField(null=True)
    dividendrate = models.TextField(null=True)
    dividendyield = models.TextField(null=True)
    earningsquarterlygrowth = models.TextField(null=True)
    enterprisetoebitda = models.TextField(null=True)
    enterprisetorevenue = models.TextField(null=True)
    enterprisevalue = models.TextField(null=True)
    exdividenddate = models.TextField(null=True)
    exchange = models.TextField(null=True)
    exchangetimezonename = models.TextField(null=True)
    exchangetimezoneshortname = models.TextField(null=True)
    expiredate = models.TextField(null=True)
    fiftydayaverage = models.TextField(null=True)
    fiftytwoweekhigh = models.TextField(null=True)
    fiftytwoweeklow = models.TextField(null=True)
    fiveyearaveragereturn = models.TextField(null=True)
    fiveyearavgdividendyield = models.TextField(null=True)
    floatshares = models.TextField(null=True)
    forwardeps = models.TextField(null=True)
    forwardpe = models.TextField(null=True)
    fromcurrency = models.TextField(null=True)
    fulltimeemployees = models.TextField(null=True)
    fundfamily = models.TextField(null=True)
    fundinceptiondate = models.TextField(null=True)
    gmtoffsetmilliseconds = models.TextField(null=True)
    heldpercentinsiders = models.TextField(null=True)
    heldpercentinstitutions = models.TextField(null=True)
    impliedsharesoutstanding = models.TextField(null=True)
    industry = models.TextField(null=True)
    isesgpopulated = models.TextField(null=True)
    lastcapgain = models.TextField(null=True)
    lastdividenddate = models.TextField(null=True)
    lastdividendvalue = models.TextField(null=True)
    lastfiscalyearend = models.TextField(null=True)
    lastmarket = models.TextField(null=True)
    lastsplitdate = models.TextField(null=True)
    lastsplitfactor = models.TextField(null=True)
    legaltype = models.TextField(null=True)
    logo_url = models.TextField(null=True)
    longbusinesssummary = models.TextField(null=True)
    longname = models.TextField(null=True)
    market = models.TextField(null=True)
    marketcap = models.TextField(null=True)
    maxage = models.TextField(null=True)
    maxsupply = models.TextField(null=True)
    messageboardid = models.TextField(null=True)
    morningstaroverallrating = models.TextField(null=True)
    morningstarriskrating = models.TextField(null=True)
    mostrecentquarter = models.TextField(null=True)
    navprice = models.TextField(null=True)
    netincometocommon = models.TextField(null=True)
    nextfiscalyearend = models.TextField(null=True)
    open_symbol = models.TextField(null=True)
    openinterest = models.TextField(null=True)
    payoutratio = models.TextField(null=True)
    pegratio = models.TextField(null=True)
    phone = models.TextField(null=True)
    previousclose = models.TextField(null=True)
    pricehint = models.TextField(null=True)
    pricetobook = models.TextField(null=True)
    pricetosalestrailing12months = models.TextField(null=True)
    profitmargins = models.TextField(null=True)
    quotetype = models.TextField(null=True)
    regularmarketdayhigh = models.TextField(null=True)
    regularmarketdaylow = models.TextField(null=True)
    regularmarketopen = models.TextField(null=True)
    regularmarketpreviousclose = models.TextField(null=True)
    regularmarketprice = models.TextField(null=True)
    regularmarketvolume = models.TextField(null=True)
    revenuequarterlygrowth = models.TextField(null=True)
    sector = models.TextField(null=True)
    sharesoutstanding = models.TextField(null=True)
    sharespercentsharesout = models.TextField(null=True)
    sharesshort = models.TextField(null=True)
    sharesshortpreviousmonthdate = models.TextField(null=True)
    sharesshortpriormonth = models.TextField(null=True)
    shortname = models.TextField(null=True)
    shortpercentoffloat = models.TextField(null=True)
    shortratio = models.TextField(null=True)
    startdate = models.TextField(null=True)
    state_symbol = models.TextField(null=True)
    strikeprice = models.TextField(null=True)
    symbol = models.TextField(null=True)
    threeyearaveragereturn = models.TextField(null=True)
    tocurrency = models.TextField(null=True)
    totalassets = models.TextField(null=True)
    tradeable = models.TextField(null=True)
    trailingannualdividendrate = models.TextField(null=True)
    trailingannualdividendyield = models.TextField(null=True)
    trailingeps = models.TextField(null=True)
    trailingpe = models.TextField(null=True)
    twohundreddayaverage = models.TextField(null=True)
    volume = models.TextField(null=True)
    volume24hr = models.TextField(null=True)
    volumeallcurrencies = models.TextField(null=True)
    website = models.TextField(null=True)
    yield_symbol = models.TextField(null=True)
    ytdreturn = models.TextField(null=True)
    zip = models.TextField(null=True)
	


