from rest_framework import serializers
from .models import Post, Stock, Symbol
from django import forms


class PostSerializer(serializers.ModelSerializer):
    class Meta:
        model = Post
        fields =(
            'title', 
            'description',
            'owner'
        )

class StockSerializer(serializers.ModelSerializer):
    class Meta:
        model = Stock
        fields =(
            'id', 
            'date', 
            'symbol', 
            'open', 
            'high', 
            'low', 
            'close', 
            'volume', 
            'dividends', 
            'stocksplits'
        )


class SymbolSerializer(serializers.ModelSerializer):
    class Meta:
        model = Symbol
        fields = (
            'id',
            'symbol_name',
            'weekchange',
            'sandp52weekchange',
            'address1',
            'algorithm',
            'annualholdingsturnover',
            'annualreportexpenseratio',
            'ask',
            'asksize',
            'averagedailyvolume10day',
            'averagevolume',
            'averagevolume10days',
            'beta',
            'beta3year',
            'bid',
            'bidsize',
            'bookvalue',
            'category',
            'circulatingsupply',
            'city',
            'companyofficers',
            'country',
            'currency',
            'dateshortinterest',
            'dayhigh',
            'daylow',
            'dividendrate',
            'dividendyield',
            'earningsquarterlygrowth',
            'enterprisetoebitda',
            'enterprisetorevenue',
            'enterprisevalue',
            'exdividenddate',
            'exchange',
            'exchangetimezonename',
            'exchangetimezoneshortname',
            'expiredate',
            'fiftydayaverage',
            'fiftytwoweekhigh',
            'fiftytwoweeklow',
            'fiveyearaveragereturn',
            'fiveyearavgdividendyield',
            'floatshares',
            'forwardeps',
            'forwardpe',
            'fromcurrency',
            'fulltimeemployees',
            'fundfamily',
            'fundinceptiondate',
            'gmtoffsetmilliseconds',
            'heldpercentinsiders',
            'heldpercentinstitutions',
            'impliedsharesoutstanding',
            'industry',
            'isesgpopulated',
            'lastcapgain',
            'lastdividenddate',
            'lastdividendvalue',
            'lastfiscalyearend',
            'lastmarket',
            'lastsplitdate',
            'lastsplitfactor',
            'legaltype',
            'logo_url',
            'longbusinesssummary',
            'longname',
            'market',
            'marketcap',
            'maxage',
            'maxsupply',
            'messageboardid',
            'morningstaroverallrating',
            'morningstarriskrating',
            'mostrecentquarter',
            'navprice',
            'netincometocommon',
            'nextfiscalyearend',
            'open_symbol',
            'openinterest',
            'payoutratio',
            'pegratio',
            'phone',
            'previousclose',
            'pricehint',
            'pricetobook',
            'pricetosalestrailing12months',
            'profitmargins',
            'quotetype',
            'regularmarketdayhigh',
            'regularmarketdaylow',
            'regularmarketopen',
            'regularmarketpreviousclose',
            'regularmarketprice',
            'regularmarketvolume',
            'revenuequarterlygrowth',
            'sector',
            'sharesoutstanding',
            'sharespercentsharesout',
            'sharesshort',
            'sharesshortpreviousmonthdate',
            'sharesshortpriormonth',
            'shortname',
            'shortpercentoffloat',
            'shortratio',
            'startdate',
            'state_symbol',
            'strikeprice',
            'symbol',
            'threeyearaveragereturn',
            'tocurrency',
            'totalassets',
            'tradeable',
            'trailingannualdividendrate',
            'trailingannualdividendyield',
            'trailingeps',
            'trailingpe',
            'twohundreddayaverage',
            'volume',
            'volume24hr',
            'volumeallcurrencies',
            'website',
            'yield_symbol',
            'ytdreturn',
            'zip'
        )